In [1]:
import os

In [2]:
import geopandas as gpd

In [3]:
filep = 'corrected/S2B_MSIL2A_20201108T054039_N9999_R005_T43SFR_20210922T185740.SAFE/GRANULE/L2A_T43SFR_A019193_20201108T055005/QI_DATA'

In [13]:
file_path = r'safe\S2A_MSIL1C_20200105T053221_N0208_R105_T43SFR_20200105T072254.SAFE\GRANULE\L1C_T43SFR_A023697_20200105T053922\QI_DATA'

In [14]:
band_map = {'cloud': 'MSK_CLOUDS_B00', 'B02': 'MSK_NODATA_B02', 'B03': 'MSK_NODATA_B03',
            'B04': 'MSK_NODATA_B04', 'B08': 'MSK_NODATA_B08'}
for band in ['cloud', 'B02', 'B03', 'B04', 'B08']:
    cmd = f'ogr2ogr -f "ESRI Shapefile" ./mask/{band}_mask.shp {img_dir+file_path}/{band_map[band]}.gml'
    r = os.system(cmd)
    print(r)

0
0
0
0
0


In [10]:
img_dir = 'N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/43SFR/'

In [6]:
train_dir = img_dir + 'train_area_sample/'

In [172]:
cloud_mask = gpd.read_file(img_dir + 'cloud_mask/L1C_T43SFR_A015289_20200209T052951/cloud_mask.shp')

In [173]:
cloud_mask

gml_id maskType                                           geometry
0      OPAQUE.0   OPAQUE  POLYGON ((676200.000 3600000.000, 676680.000 3...
1      OPAQUE.1   OPAQUE  POLYGON ((642120.000 3599700.000, 642300.000 3...
2      OPAQUE.2   OPAQUE  POLYGON ((636000.000 3599340.000, 636240.000 3...
3      OPAQUE.3   OPAQUE  POLYGON ((643200.000 3598740.000, 643380.000 3...
4      OPAQUE.4   OPAQUE  POLYGON ((634560.000 3598680.000, 634740.000 3...
..          ...      ...                                                ...
698  CIRRUS.579   CIRRUS  POLYGON ((708300.000 3492180.000, 708540.000 3...
699  CIRRUS.580   CIRRUS  POLYGON ((699780.000 3490740.000, 700020.000 3...
700  CIRRUS.581   CIRRUS  POLYGON ((671640.000 3490440.000, 672000.000 3...
701  CIRRUS.582   CIRRUS  POLYGON ((704100.000 3491340.000, 704280.000 3...
702  CIRRUS.583   CIRRUS  POLYGON ((708600.000 3490800.000, 708780.000 3...

[703 rows x 3 columns]

In [53]:
cloud_mask_proj

gml_id maskType                                           geometry
0     OPAQUE.0   OPAQUE  POLYGON ((76.19815 32.12627, 76.20133 32.12624...
1     OPAQUE.1   OPAQUE  POLYGON ((76.16356 32.10656, 76.16546 32.10655...
2     OPAQUE.2   OPAQUE  POLYGON ((76.72012 32.08237, 76.72266 32.08233...
3     OPAQUE.3   OPAQUE  POLYGON ((76.18225 32.07716, 76.18480 32.07714...
4     OPAQUE.4   OPAQUE  POLYGON ((76.18731 32.07495, 76.18985 32.07493...
..         ...      ...                                                ...
265  CIRRUS.19   CIRRUS  POLYGON ((76.80571 31.97402, 76.80762 31.97399...
266  CIRRUS.20   CIRRUS  POLYGON ((76.66648 31.92830, 76.66838 31.92827...
267  CIRRUS.21   CIRRUS  POLYGON ((76.62396 31.92831, 76.62586 31.92828...
268  CIRRUS.22   CIRRUS  POLYGON ((76.72468 31.91832, 76.72658 31.91829...
269  CIRRUS.23   CIRRUS  POLYGON ((76.74424 31.91264, 76.74678 31.91261...

[270 rows x 3 columns]

In [19]:
cloud_mask.crs

<Projected CRS: EPSG:32643>
Name: WGS 84 / UTM zone 43N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 72°E and 78°E, northern hemisphere between equator and 84°N, onshore and offshore. China. India. Kazakhstan. Kyrgyzstan. Maldives. Pakistan. Russian Federation. Tajikistan.
- bounds: (72.0, 0.0, 78.0, 84.0)
Coordinate Operation:
- name: UTM zone 43N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [174]:
meta

{'driver': 'GTiff',
 'dtype': 'uint16',
 'nodata': None,
 'width': 1892,
 'height': 2357,
 'count': 4,
 'crs': CRS.from_epsg(4326),
 'transform': Affine(9.810891648968448e-05, 0.0, 77.03211244126558,
        0.0, -9.810891648968448e-05, 32.25451163012633)}

In [187]:
cloud_shp = cloud_mask
cloud_legend = {'CLOUDLESS': 0, 'OPAQUE': 1, 'CIRRUS': 2}
shapes = iter([(shapely.geometry.mapping(poly), cloud_legend[v]) for poly, v in
               zip(cloud_shp.geometry, cloud_shp.maskType)])
cloud_img = rasterio.features.rasterize(shapes, out_shape=(eg_meta['height'], eg_meta['width']),
                                        transform=eg_meta['transform'])

In [186]:
eg_meta, meta

({'driver': 'JP2OpenJPEG',
  'dtype': 'uint16',
  'nodata': None,
  'width': 10980,
  'height': 10980,
  'count': 5,
  'crs': None,
  'transform': Affine(10.0, 0.0, 600000.0,
         0.0, -10.0, 3600000.0)},
 {'driver': 'GTiff',
  'dtype': 'uint16',
  'nodata': None,
  'width': 1892,
  'height': 2357,
  'count': 4,
  'crs': CRS.from_epsg(4326),
  'transform': Affine(9.810891648968448e-05, 0.0, 77.03211244126558,
         0.0, -9.810891648968448e-05, 32.25451163012633)})

In [188]:
cloud_img

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [189]:
np.unique(cloud_img)

array([0, 1, 2], dtype=uint8)

In [3]:
import os
import re
import sys
import math
import fiona
import pickle
import logging
import datetime
import numpy as np
import pandas as pd
import geopandas as gpd
import skimage
import skimage.draw
import pyproj
import rasterio
from rasterio.mask import mask
from rasterio.warp import calculate_default_transform, reproject, Resampling

C:\Users\lida\Anaconda3\envs\ch\lib\site-packages\geopandas\_compat.py:106: UserWarning: The Shapely GEOS version (3.8.0-CAPI-1.13.1 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.1-CAPI-1.14.2). Conversions between both will be slow.
  warnings.warn(


In [4]:
def load_target_shp(path, transform=None, proj_out=None):
    """ Load the shapefile as a list of numpy array of coordinates
        INPUT : path (str) -> the path to the shapefile
                transform (rasterio.Affine) -> the affine transformation to get the polygon in row;col format from UTM.
        OUTPUT : poly (list of np.array) -> list of polygons (as numpy.array of coordinates)
                 poly_rc (list of np.array) -> list of polygon in row-col format if a transform is given
    """
    print("Loading target shapefile...")
    with fiona.open(path) as shapefile:
        proj_in = pyproj.Proj(shapefile.crs)
        class_type = [1 for feature in shapefile]
        features = [feature["geometry"] for feature in shapefile]
    # re-project polygons if necessary
    if proj_out is None or proj_in == proj_out:
        poly = [np.array([(coord[0], coord[1]) for coord in features[i]['coordinates'][0]]) for i in
                range(len(features))]
        print('No re-projection!')
    else:
        poly = [np.array(
            [pyproj.transform(proj_in, proj_out, coord[0], coord[1]) for coord in features[i]['coordinates'][0]]) for i
            in range(len(features))]
        print(f'Re-project from {proj_in} to {proj_out}')

    poly_rc = None
    # transform in row-col if a transform is given
    if transform is not None:
        poly_rc = [np.array([rasterio.transform.rowcol(transform, coord[0], coord[1])[::-1] for coord in p]) for p in
                   poly]
    print('Loaded target shape files.')

    return features, poly, poly_rc, class_type


def compute_mask(polygon_list, meta, val_list):
    """ Get mask of class of a polygon list
        INPUT : polygon_list (list od polygon in coordinates (x, y)) -> the polygons in row;col format
                meta -> the image width and height
                val_list(list of int) -> the class associated with each polygon
        OUTPUT : img (np.array 2D) -> the mask in which the pixel value reflect it's class (zero being the absence of class)
    """
    img = np.zeros((meta['height'], meta['width']), dtype=np.uint8)  # skimage : row,col --> h,w
    i = 0
    for polygon, val in zip(polygon_list, val_list):
        rr, cc = skimage.draw.polygon(polygon[:, 1], polygon[:, 0], img.shape)
        img[rr, cc] = val
        i += 1
    print("Added targets' mask.")
    return img


def load_geotiff(path, window=None):
    """ Load the geotiff as a list of numpy array.
        INPUT : path (str) -> the path to the geotiff
                window (rasterio.windows.Window) -> the window to use when loading the image
        OUTPUT : band (list of numpy array) -> the different bands as float scaled to 0:1
                 meta (dictionary) -> the metadata associated with the geotiff
    """
    with rasterio.open(path) as f:
        band = [skimage.img_as_float(f.read(i + 1, window=window)) for i in range(f.count)]
        meta = f.meta
        if window is not None:
            meta['height'] = window.height
            meta['width'] = window.width
            meta['transform'] = f.window_transform(window)
    return band, meta

In [36]:
eg = img_dir + 'train_area/L2A_T43SFR_A026271_20200703T053446.tiff'
band, meta = load_geotiff(eg)

In [37]:
features, poly, poly_rc, class_type = load_target_shp('./cloud_mask/cloud_mask.shp', meta['transform'], pyproj.Proj(meta['crs']))

Loading target shapefile...


C:\Users\lida\Anaconda3\envs\ch\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\lida\AppData\Local\Temp/ipykernel_17832/2398201670.py:20: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  [pyproj.transform(proj_in, proj_out, coord[0], coord[1]) for coord in features[i]['coordinates'][0]]) for i


KeyboardInterrupt: 

In [38]:
train_area_shp = gpd.read_file('../data/train_area/train_area.shp')

In [54]:
train_area_shp['geometry'].overlay(cloud_mask_proj, how='intersection')

AttributeError: 'GeoSeries' object has no attribute 'overlay'

In [69]:
df = train_area_shp.geometry.intersection(cloud_mask_proj.geometry)

C:\Users\lida\Anaconda3\envs\ch\lib\site-packages\geopandas\base.py:32: UserWarning: The indices of the two GeoSeries are different.
  warn("The indices of the two GeoSeries are different.")


In [85]:
df.is_empty

0       True
1      False
2      False
3      False
4      False
       ...  
265    False
266    False
267    False
268    False
269    False
Length: 270, dtype: bool

In [87]:
df == None

0      False
1       True
2       True
3       True
4       True
       ...  
265     True
266     True
267     True
268     True
269     True
Length: 270, dtype: bool

In [96]:
a = df[(df != None) & (~df.is_empty)]

In [101]:
a

GeoSeries([], dtype: geometry)

In [102]:
a.shape 

(0,)

In [66]:
dff = train_area_shp.sjoin(cloud_mask_proj, how='intersection')

AttributeError: 'GeoDataFrame' object has no attribute 'sjoin'

In [56]:
train_area_shp

id                                           geometry
0   0  POLYGON ((77.17355 32.23500, 77.20571 32.25445...

In [46]:
train_area_shp.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [50]:
meta['crs']

CRS.from_epsg(4326)

In [51]:
cloud_mask_proj = cloud_mask.to_crs(meta['crs'])

In [ ]:
cloud_mask_proj.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- undefined
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [58]:
from shapely.geometry import Polygon
polys1 = gpd.GeoSeries([Polygon([(0,0), (2,0), (2,2), (0,2)]),
                              Polygon([(2,2), (4,2), (4,4), (2,4)])])
polys2 = gpd.GeoSeries([Polygon([(1,1), (3,1), (3,3), (1,3)]),
                              Polygon([(3,3), (5,3), (5,5), (3,5)])])
df1 = gpd.GeoDataFrame({'geometry': polys1, 'df1_data':[1,2]})
df2 = gpd.GeoDataFrame({'geometry': polys2, 'df2_data':[1,2]})

In [61]:
df1.intersection(df2)

0    POLYGON ((2.00000 2.00000, 2.00000 1.00000, 1....
1    POLYGON ((4.00000 4.00000, 4.00000 3.00000, 3....
dtype: geometry

In [67]:
df1.sjoin(df2, how='intersection')

AttributeError: 'GeoDataFrame' object has no attribute 'sjoin'

### build cloud_mask from gml to shp

In [122]:
def convert_gml_to_shp(img_dir):
    safe_dir = img_dir + 'safe/'
    cloud_dir = img_dir + 'cloud_mask/'
    if not os.path.exists(cloud_dir):
        os.mkdir(cloud_dir)

    safe_names = os.listdir(safe_dir)

    print('Converting cloud mask from gml to shp ...')
    for i, safe_name in enumerate(safe_names, start=1):
        filename = os.listdir(safe_dir + safe_name + '/GRANULE/')[0]
        gml_path = safe_dir + safe_name + '/GRANULE/' + filename + '/QI_DATA/MSK_CLOUDS_B00.gml'
        if not os.path.exists(cloud_dir + filename):
            os.mkdir(cloud_dir + filename)
        cloud_path = cloud_dir + filename + '/cloud_mask.shp'
        cmd = f'ogr2ogr -f "ESRI Shapefile" {cloud_path} {gml_path}'
        returned = os.system(cmd)
        if returned == 0:
            print(f'[{i}/{len(safe_names)}] {cloud_path} ')
        else:
            raise ValueError(f'{safe_name} failed')
    print(f'  ok')

In [123]:
convert_gml_to_shp(img_dir)

Converting cloud mask from gml to shp ...
[1/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A023697_20200105T053922/cloud_mask.shp 
[2/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A023740_20200108T054215/cloud_mask.shp 
[3/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A023840_20200115T053150/cloud_mask.shp 
[4/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A023883_20200118T054145/cloud_mask.shp 
[5/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A023983_20200125T053846/cloud_mask.shp 
[6/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A024026_20200128T054632/cloud_mask.shp 
[7/131] N:/dataorg-datasets/MLsatellite/sentinel2_images/images_danya/cloud_mask/L1C_T43SFR_A024126_20200204T053431/cloud_mask.shp 
[8/131] N:/dataorg-datasets/MLsate

In [124]:
filepath = img_dir + 'safe/S2B_MSIL1C_20201225T053229_N0209_R105_T43SFR_20201225T064223.SAFE/GRANULE/L1C_T43SFR_A019865_20201225T053231/IMG_DATA/T43SFR_20201225T053229_B02.jp2'
with rasterio.open(filepath) as src:
    b = src.read(1)

In [126]:
b

array([[   0,    0,    0, ..., 8016, 7260, 7454],
       [   0,    0,    0, ..., 8102, 7893, 7812],
       [   0,    0,    0, ..., 7658, 7942, 7851],
       ...,
       [   0,    0,    0, ...,  644,  652,  661],
       [   0,    0,    0, ...,  655,  666,  658],
       [   0,    0,    0, ...,  652,  652,  674]], dtype=uint16)

In [128]:
c = gpd.read_file(img_dir + 'cloud_mask/L1C_T43SFR_A014860_20200110T053549/cloud_mask.shp')

In [132]:
c

gml_id maskType                                           geometry
0      OPAQUE.0   OPAQUE  POLYGON ((634260.000 3600000.000, 634560.000 3...
1      OPAQUE.1   OPAQUE  POLYGON ((639900.000 3600000.000, 640860.000 3...
2      OPAQUE.2   OPAQUE  POLYGON ((634920.000 3599580.000, 635100.000 3...
3      OPAQUE.3   OPAQUE  POLYGON ((636000.000 3599340.000, 636240.000 3...
4      OPAQUE.4   OPAQUE  POLYGON ((643320.000 3598740.000, 643500.000 3...
..          ...      ...                                                ...
702  CIRRUS.411   CIRRUS  POLYGON ((670620.000 3490800.000, 670800.000 3...
703  CIRRUS.412   CIRRUS  POLYGON ((702960.000 3490740.000, 703140.000 3...
704  CIRRUS.413   CIRRUS  POLYGON ((672480.000 3493500.000, 672720.000 3...
705  CIRRUS.414   CIRRUS  POLYGON ((697380.000 3491100.000, 697560.000 3...
706  CIRRUS.415   CIRRUS  POLYGON ((698820.000 3490440.000, 699120.000 3...

[707 rows x 3 columns]

In [135]:
cloud_legend = {'OPAQUE': 1, 'CIRRUS': 2}

In [137]:
import shapely

In [138]:
shapes = iter([(shapely.geometry.mapping(poly), cloud_legend[v]) for poly, v in zip(c.geometry, c.maskType)])
cloud_img = rasterio.features.rasterize(shapes, out_shape=(meta['height'], meta['width']),
                                       transform=meta['transform'])

In [140]:
cloud_img.shape

(2357, 1892)

In [141]:
np.unique(cloud_img)

array([0], dtype=uint8)

In [144]:
'L2A'+'L1C_T43SFR_A014760_20200103T054832'.lstrip('L1C')

'L2A_T43SFR_A014760_20200103T054832'

In [159]:
a = gpd.GeoDataFrame([{'gml_id': 'CLOUDLESS.0', 'maskType': 'CLOUDLESS', 'geometry': shapely.geometry.Polygon()}])

In [160]:
a

gml_id   maskType                  geometry
0  CLOUDLESS.0  CLOUDLESS  GEOMETRYCOLLECTION EMPTY

In [161]:
a.to_file('out.shp', driver='ESRI Shapefile')

DriverIOError: Geometry type of 'Geometry Collection' not supported in shapefiles.  Type can be overridden with a layer creation option of SHPT=POINT/ARC/POLYGON/MULTIPOINT/POINTZ/ARCZ/POLYGONZ/MULTIPOINTZ/MULTIPATCH.

In [190]:
eg_band, eg_meta = load_geotiff(img_dir + 'geotiff/L2A_T43SFR_A023697_20200105T053922.tiff')

In [191]:
eg_meta

{'driver': 'JP2OpenJPEG',
 'dtype': 'uint16',
 'nodata': None,
 'width': 10980,
 'height': 10980,
 'count': 5,
 'crs': None,
 'transform': Affine(10.0, 0.0, 600000.0,
        0.0, -10.0, 3600000.0)}

In [192]:
np.unique(eg_band[-1])

array([0.00000000e+00, 1.52590219e-05, 3.05180438e-05, 4.57770657e-05,
       6.10360876e-05, 7.62951095e-05, 9.15541314e-05])

In [171]:
eg_band[-1]

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.52590219e-05, 1.52590219e-05, 1.52590219e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.52590219e-05, 1.52590219e-05, 1.52590219e-05],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.52590219e-05, 1.52590219e-05, 1.52590219e-05],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [197]:
with rasterio.open(img_dir + 'geotiff/L2A_T43SFR_A023697_20200105T053922.tiff') as src:
    arr1 = src.read(1)
    arr5 = src.read(5)

In [198]:
arr1.max()

19410

In [238]:
arr1.dtype

dtype('uint16')

In [199]:
arr1[:5]

array([[    0,     0,     0, ..., 15869, 16183, 16400],
       [    0,     0,     0, ..., 15281, 15990, 16505],
       [    0,     0,     0, ..., 14484, 15405, 16114],
       [    0,     0,     0, ..., 13933, 14675, 15298],
       [    0,     0,     0, ..., 13614, 14104, 14708]], dtype=uint16)

In [200]:
arr5[:5]

array([[0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1],
       [0, 0, 0, ..., 1, 1, 1]], dtype=uint16)

In [27]:
def count(arr):
    for v in np.unique(arr):
        print(f'v={v}, count={(arr == v).sum()}')

In [2]:
def load_geotiff_int(path, window=None):
    """ Load the geotiff as a list of numpy array.
        INPUT : path (str) -> the path to the geotiff
                window (rasterio.windows.Window) -> the window to use when loading the image
        OUTPUT : band (list of numpy array) -> the different bands as float scaled to 0:1
                 meta (dictionary) -> the metadata associated with the geotiff
    """
    with rasterio.open(path) as f:
        band = [skimage.img_as_uint(f.read(i + 1, window=window)) for i in range(f.count)]
        meta = f.meta
        if window is not None:
            meta['height'] = window.height
            meta['width'] = window.width
            meta['transform'] = f.window_transform(window)
    return band, meta

In [35]:
eg_band_int, eg_meta_int = load_geotiff_int(img_dir + 'geotiff/L2A_T43SFR_A023697_20200105T053922.tiff')

KeyboardInterrupt: 

In [ ]:
eg_meta_int

In [ ]:
count(eg_band_int[-1])

In [68]:
with rasterio.open(img_dir + 'geotiff/L2A_T43SFR_A023697_20200105T053922.tiff') as src:
    des = src.descriptions
    arr1 = src.read(1)
    arr5 = src.read(5)

In [64]:
count(arr5)

v=0, count=25677828
v=1, count=74599164
v=2, count=20283408


In [65]:
arr1.max()

19344

In [69]:
des

('B02', 'B03', 'B04', 'B08', 'cloud mask')

In [39]:
25677828 + 74599164 + 20283408

120560400

In [24]:
10980*10980

120560400

In [226]:
meta_ = eg_meta.copy()
meta_.update(count=2)

In [232]:
meta_

{'driver': 'JP2OpenJPEG',
 'dtype': 'uint16',
 'nodata': None,
 'width': 10980,
 'height': 10980,
 'count': 2,
 'crs': None,
 'transform': Affine(10.0, 0.0, 600000.0,
        0.0, -10.0, 3600000.0)}

In [227]:
with rasterio.open('out.tiff', 'w', **meta_) as dst:
    cloud_shp = gpd.read_file(img_dir + 'cloud_mask/L1C_T43SFR_A015289_20200209T052951/cloud_mask.shp')
    shapes = iter([(shapely.geometry.mapping(poly), cloud_legend[v]) for poly, v in
                   zip(cloud_shp.geometry, cloud_shp.maskType)])
    cloud_img = rasterio.features.rasterize(shapes, out_shape=(meta_['height'], meta_['width']),
                                            transform=meta_['transform'])
    dst.write_band(1, cloud_img)
    dst.write_band(2, np.zeros((meta_['height'], meta_['width'])))

In [228]:
band_out, meta_out = load_geotiff_int('out.tiff')

In [231]:
np.unique(band_out[0])

array([0, 1, 2, 3], dtype=uint16)

In [48]:
rasterio.crs.CRS.from_epsg(32643)

CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: cannot build projectedCRS 32643: SQLite error on SELECT extent.description, extent.south_lat, extent.north_lat, extent.west_lon, extent.east_lon, scope.scope, (CASE WHEN scope.scope LIKE '%large scale%' THEN 0 ELSE 1 END) AS score FROM usage JOIN extent ON usage.extent_auth_name = extent.auth_name AND usage.extent_code = extent.code JOIN scope ON usage.scope_auth_name = scope.auth_name AND usage.scope_code = scope.code WHERE object_table_name = ? AND object_auth_name = ? AND object_code = ? ORDER BY score, usage.auth_name, usage.code: no such table: usage

In [53]:
rasterio.crs.CRS.from_string('WGS84')

CRS.from_epsg(4326)

In [54]:
rasterio.crs.CRS.from_string('EPSG:32643')

CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: cannot build projectedCRS 32643: SQLite error on SELECT extent.description, extent.south_lat, extent.north_lat, extent.west_lon, extent.east_lon, scope.scope, (CASE WHEN scope.scope LIKE '%large scale%' THEN 0 ELSE 1 END) AS score FROM usage JOIN extent ON usage.extent_auth_name = extent.auth_name AND usage.extent_code = extent.code JOIN scope ON usage.scope_auth_name = scope.auth_name AND usage.scope_code = scope.code WHERE object_table_name = ? AND object_auth_name = ? AND object_code = ? ORDER BY score, usage.auth_name, usage.code: no such table: usage

In [56]:
rasterio.crs.CRS.from_epsg(32643)

CRSError: The EPSG code is unknown. PROJ: proj_create_from_database: cannot build projectedCRS 32643: SQLite error on SELECT extent.description, extent.south_lat, extent.north_lat, extent.west_lon, extent.east_lon, scope.scope, (CASE WHEN scope.scope LIKE '%large scale%' THEN 0 ELSE 1 END) AS score FROM usage JOIN extent ON usage.extent_auth_name = extent.auth_name AND usage.extent_code = extent.code JOIN scope ON usage.scope_auth_name = scope.auth_name AND usage.scope_code = scope.code WHERE object_table_name = ? AND object_auth_name = ? AND object_code = ? ORDER BY score, usage.auth_name, usage.code: no such table: usage

In [58]:
crs = pyproj.CRS('EPSG:32643')
crs

<Projected CRS: EPSG:32643>
Name: WGS 84 / UTM zone 43N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 72°E and 78°E, northern hemisphere between equator and 84°N, onshore and offshore. China. India. Kazakhstan. Kyrgyzstan. Maldives. Pakistan. Russian Federation. Tajikistan.
- bounds: (72.0, 0.0, 78.0, 84.0)
Coordinate Operation:
- name: UTM zone 43N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [59]:
rasterio.crs.CRS.to_wkt(crs)

TypeError: to_wkt() got an unexpected keyword argument 'morph_to_esri_dialect'

In [60]:
rasterio.crs.CRS.from_user_input(crs)

CRS.from_epsg(32643)

In [95]:
import geopandas

In [116]:
data = geopandas.read_file('../data/train_area/train_area.shp')
data

id                                           geometry
0   0  POLYGON ((77.17355 32.23500, 77.20571 32.25445...

In [117]:
data = data.to_crs(32643)
data

id                                           geometry
0   0  POLYGON ((704799.374 3568556.621, 707786.270 3...

In [114]:
data = data.to_crs(pyproj.CRS('epsg:32643'))
data

id                                           geometry
0   0  POLYGON ((704799.374 3568556.621, 707786.270 3...

In [111]:
with fiona.Env(OSR_WKT_FORMAT="WKT2_2018"):
    data.to_file('./reprojected.shp')

with fiona.Env(OSR_WKT_FORMAT="WKT2_2018"):
     r = geopandas.read_file("./reprojected.shp")

In [112]:
r.crs

<Projected CRS: EPSG:32643>
Name: WGS 84 / UTM zone 43N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 72°E and 78°E, northern hemisphere between equator and 84°N, onshore and offshore. China. India. Kazakhstan. Kyrgyzstan. Maldives. Pakistan. Russian Federation. Tajikistan.
- bounds: (72.0, 0.0, 78.0, 84.0)
Coordinate Operation:
- name: UTM zone 43N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [103]:
import geopandas as gpd
from shapely.geometry import Polygon

polygon = Polygon([[-93.448499, 42.721669],[-93.447275, 42.722667],[-93.445998, 42.720974],[-93.448499, 42.721669]])

df = gpd.GeoDataFrame({'NAME':['poly1'], 'geometry':[polygon]}, crs='EPSG:4326')

target_crs = 'PROJCS["IaRCS_04_Sioux_City-Iowa_Falls_NAD_1983_2011_LCC_US_Feet",GEOGCS["GCS_NAD_1983_2011",DATUM["D_NAD_1983_2011",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",14500000.0],PARAMETER["False_Northing",8600000.0],PARAMETER["Central_Meridian",-94.83333333333333],PARAMETER["Standard_Parallel_1",42.53333333333333],PARAMETER["Standard_Parallel_2",42.53333333333333],PARAMETER["Scale_Factor",1.000045],PARAMETER["Latitude_Of_Origin",42.53333333333333],UNIT["Foot_US",0.3048006096012192]]'
df.to_crs(target_crs, inplace=True)

with fiona.Env(OSR_WKT_FORMAT="WKT2_2018"):
    df.to_file('./test.shp')


In [104]:
with fiona.Env(OSR_WKT_FORMAT="WKT2_2018"):
     r = geopandas.read_file("./test.shp")

In [106]:
r.crs

<Projected CRS: PROJCRS["IaRCS_04_Sioux_City-Iowa_Falls_NAD_1983_2 ...>
Name: IaRCS_04_Sioux_City-Iowa_Falls_NAD_1983_2011_LCC_US_Feet
Axis Info [cartesian]:
- E[east]: Easting (US survey foot)
- N[north]: Northing (US survey foot)
Area of Use:
- undefined
Coordinate Operation:
- name: unnamed
- method: Lambert Conic Conformal (2SP Michigan)
Datum: NAD83 (National Spatial Reference System 2011)
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [119]:
raster = rasterio.open(r'N:\dataorg-datasets\MLsatellite\sentinel2_images\images_danya\43SFR\train_region\L2A_T43SFR_A015003_20200120T053410.tiff')

In [123]:
arr5 = raster.read(5)

In [124]:
count(arr5)

v=0, count=3777419
v=1, count=1064788
v=2, count=34056


In [125]:
arr5.shape

(2669, 1827)

## cloud mask from SCL

In [1]:
file = r'N:\dataorg-datasets\MLsatellite\sentinel2_images\images_danya\43SFR\L2A\S2B_MSIL2A_20201228T054239_N9999_R005_T43SFR_20210923T025012.SAFE\GRANULE\L2A_T43SFR_A019908_20201228T054233\IMG_DATA\R60m\T43SFR_20201228T054239_SCL_60m.jp2'

In [2]:
import rasterio

In [4]:
data = rasterio.open(file)

In [6]:
data.crs

CRS.from_epsg(32643)

In [36]:
data.shape

(1830, 1830)

In [37]:
def resample(in_file, h_target, w_target):
    with rasterio.open(in_file) as dataset:
        # resample data to target shape
        data = dataset.read(
            out_shape=(dataset.count, h_target, w_target),
            resampling=Resampling.nearest
        )

        # scale image transform
        transform = dataset.transform * dataset.transform.scale(
            (dataset.width / w_target),
            (dataset.height / h_target)
        )

        return data, transform

In [39]:
from rasterio.enums import Resampling

In [40]:
resampled_data, transf = resample(file, 10980, 10980)

In [41]:
resampled_data.shape

(1, 10980, 10980)

In [46]:
import numpy as np

In [47]:
resampled_data = np.squeeze(resampled_data)

In [48]:
resampled_data.shape

(10980, 10980)

In [7]:
import geopandas as gpd

In [9]:
cloud_name = r'N:\dataorg-datasets\MLsatellite\sentinel2_images\images_danya\43SFR\cloud_mask\L1C_T43SFR_A014760_20200103T054832\cloud_mask.shp'
cloud = gpd.read_file(cloud_name)

In [10]:
cloud.crs

<Projected CRS: EPSG:32643>
Name: WGS 84 / UTM zone 43N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: Between 72°E and 78°E, northern hemisphere between equator and 84°N, onshore and offshore. China. India. Kazakhstan. Kyrgyzstan. Maldives. Pakistan. Russian Federation. Tajikistan.
- bounds: (72.0, 0.0, 78.0, 84.0)
Coordinate Operation:
- name: UTM zone 43N
- method: Transverse Mercator
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [28]:
import os

def find_file(string, search_path):
    result = []

    # Wlaking top-down from the root
    for root, dir_, files in os.walk(search_path):
        flag = False
        for f in files:
            if string in f:
                flag = True
                filename = f
                result.append(os.path.join(root, filename))
                break
            
    return result

In [30]:
search_path = r'N:\dataorg-datasets\MLsatellite\sentinel2_images\images_danya\43SFR\L2A\S2B_MSIL2A_20200817T052649_N9999_R105_T43SFR_20210923T075853.SAFE'
find_file('B02_10m.jp2', search_path)

['N:\\dataorg-datasets\\MLsatellite\\sentinel2_images\\images_danya\\43SFR\\L2A\\S2B_MSIL2A_20200817T052649_N9999_R105_T43SFR_20210923T075853.SAFE\\GRANULE\\L2A_T43SFR_A018006_20200817T053152\\IMG_DATA\\R10m\\T43SFR_20200817T052649_B02_10m.jp2']

In [34]:
scene_legend = ['NO_DATA', 'SATURATED_OR_DEFECTIVE', 'DARK_AREA_PIXELS', 'CLOUD_SHADOWS', 'VEGETATION', 'NOT_VEGETATED', 'WATER', 'UNCLASSIFIED', 'CLOUD_MEDIUM_PROBABILITY']
d = dict(zip(scene_legend, range(len(scene_legend))))

In [35]:
d

{'NO_DATA': 0,
 'SATURATED_OR_DEFECTIVE': 1,
 'DARK_AREA_PIXELS': 2,
 'CLOUD_SHADOWS': 3,
 'VEGETATION': 4,
 'NOT_VEGETATED': 5,
 'WATER': 6,
 'UNCLASSIFIED': 7,
 'CLOUD_MEDIUM_PROBABILITY': 8}